/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    'image-assets': ImageAsset;
    projects: Project;
    testimonials: Testimonial;
    leads: Lead;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    'image-assets': ImageAssetsSelect<false> | ImageAssetsSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    leads: LeadsSelect<false> | LeadsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('ro' | 'en') | ('ro' | 'en')[];
  globals: {
    'site-settings': SiteSetting;
    'navigation-footer': NavigationFooter;
    'home-page': HomePage;
    'gallery-page': GalleryPage;
    'about-page': AboutPage;
    'pricing-settings': PricingSetting;
    services: Service;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    'navigation-footer': NavigationFooterSelect<false> | NavigationFooterSelect<true>;
    'home-page': HomePageSelect<false> | HomePageSelect<true>;
    'gallery-page': GalleryPageSelect<false> | GalleryPageSelect<true>;
    'about-page': AboutPageSelect<false> | AboutPageSelect<true>;
    'pricing-settings': PricingSettingsSelect<false> | PricingSettingsSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
  };
  locale: 'ro' | 'en';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  /**
   * Internal display name for the Payload admin.
   */
  name?: string | null;
  role: 'admin' | 'editor';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "image-assets".
 */
export interface ImageAsset {
  id: number;
  /**
   * Horizontal focal point for cropped images, in percent.
   */
  focalX?: number | null;
  /**
   * Vertical focal point for cropped images, in percent.
   */
  focalY?: number | null;
  title: string;
  /**
   * Public alt text. Keep it descriptive for SEO and accessibility.
   */
  alt: string;
  intendedUsage?: ('library' | 'logo' | 'hero' | 'project' | 'gallery' | 'about' | 'og')[] | null;
  preferredVariant: 'auto' | 'original' | '2k' | '1080';
  uploadStatus: 'draft' | 'uploading' | 'ready' | 'failed';
  /**
   * Provider metadata is intentionally hidden from editors. Hetzner migration belongs in the storage layer.
   */
  storageProvider?: ('digi_storage' | 'hetzner_storage') | null;
  adminThumbnailUrl?: string | null;
  originalFilename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  variants?: {
    original?: {
      url?: string | null;
      digiStoragePath?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
    };
    twoK?: {
      url?: string | null;
      digiStoragePath?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
    };
    hd1080?: {
      url?: string | null;
      digiStoragePath?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
    };
    thumbnail?: {
      url?: string | null;
      digiStoragePath?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
    };
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: number;
  publication: 'draft' | 'demo' | 'published';
  audience?: ('residential' | 'commercial') | null;
  /**
   * Matching Pricing Settings finish ID, if applicable.
   */
  finishId?: string | null;
  /**
   * Matching Pricing Settings lighting ID, if applicable.
   */
  lightingId?: string | null;
  details?: string | null;
  technicalDetails?: string | null;
  title: string;
  slug: string;
  city?: string | null;
  areaSqm?: number | null;
  ceilingType?: string | null;
  summary: string;
  mainImage?: (number | null) | ImageAsset;
  images?: (number | ImageAsset)[] | null;
  featured?: boolean | null;
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number;
  /**
   * Publish only genuine testimonials approved for public use.
   */
  approved?: boolean | null;
  clientName: string;
  city?: string | null;
  headline?: string | null;
  quote: string;
  /**
   * Longer article-style testimonial content. The public card uses quote/headline first.
   */
  story?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  relatedProject?: (number | null) | Project;
  image?: (number | null) | ImageAsset;
  rating?: number | null;
  featured?: boolean | null;
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads".
 */
export interface Lead {
  id: number;
  requestKey?: string | null;
  notificationStatus?: ('pending' | 'sent' | 'failed' | 'skipped') | null;
  name: string;
  phone: string;
  email?: string | null;
  city?: string | null;
  message?: string | null;
  preferredContact: 'whatsapp' | 'phone' | 'email';
  locale: 'ro' | 'en';
  calculatorInput?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  pricingSnapshot?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  estimateRonMin?: number | null;
  estimateRonMax?: number | null;
  estimateEurMin?: number | null;
  estimateEurMax?: number | null;
  source?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'image-assets';
        value: number | ImageAsset;
      } | null)
    | ({
        relationTo: 'projects';
        value: number | Project;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: number | Testimonial;
      } | null)
    | ({
        relationTo: 'leads';
        value: number | Lead;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "image-assets_select".
 */
export interface ImageAssetsSelect<T extends boolean = true> {
  focalX?: T;
  focalY?: T;
  title?: T;
  alt?: T;
  intendedUsage?: T;
  preferredVariant?: T;
  uploadStatus?: T;
  storageProvider?: T;
  adminThumbnailUrl?: T;
  originalFilename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  variants?:
    | T
    | {
        original?:
          | T
          | {
              url?: T;
              digiStoragePath?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
            };
        twoK?:
          | T
          | {
              url?: T;
              digiStoragePath?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
            };
        hd1080?:
          | T
          | {
              url?: T;
              digiStoragePath?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
            };
        thumbnail?:
          | T
          | {
              url?: T;
              digiStoragePath?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  publication?: T;
  audience?: T;
  finishId?: T;
  lightingId?: T;
  details?: T;
  technicalDetails?: T;
  title?: T;
  slug?: T;
  city?: T;
  areaSqm?: T;
  ceilingType?: T;
  summary?: T;
  mainImage?: T;
  images?: T;
  featured?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  approved?: T;
  clientName?: T;
  city?: T;
  headline?: T;
  quote?: T;
  story?: T;
  relatedProject?: T;
  image?: T;
  rating?: T;
  featured?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads_select".
 */
export interface LeadsSelect<T extends boolean = true> {
  requestKey?: T;
  notificationStatus?: T;
  name?: T;
  phone?: T;
  email?: T;
  city?: T;
  message?: T;
  preferredContact?: T;
  locale?: T;
  calculatorInput?: T;
  pricingSnapshot?: T;
  estimateRonMin?: T;
  estimateRonMax?: T;
  estimateEurMin?: T;
  estimateEurMax?: T;
  source?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  brandName: string;
  domain: string;
  /**
   * Use the final approved logo asset here when available.
   */
  logoImage?: (number | null) | ImageAsset;
  /**
   * Public phone number as displayed.
   */
  phone?: string | null;
  email?: string | null;
  /**
   * Use international format without spaces for best WhatsApp links, e.g. 407XXXXXXXX.
   */
  whatsappNumber?: string | null;
  facebookUrl?: string | null;
  instagramUrl?: string | null;
  /**
   * Optional public company name for footer/legal context.
   */
  legalName?: string | null;
  /**
   * Optional public registry/tax identifier. Confirm before final launch.
   */
  registrationNumber?: string | null;
  mainCity?: string | null;
  serviceArea?: string | null;
  serviceCities?:
    | {
        city: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Brand palette locked for the public design.
   */
  palette: {
    warmNeutral: string;
    orange: string;
    blue: string;
    black: string;
  };
  seo: {
    title: string;
    description: string;
    defaultOgImage?: (number | null) | ImageAsset;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation-footer".
 */
export interface NavigationFooter {
  id: number;
  headerLinks?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  footerLinks?:
    | {
        label: string;
        href: string;
        newTab?: boolean | null;
        id?: string | null;
      }[]
    | null;
  footerText?: string | null;
  creditLabel?: string | null;
  creditHref?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page".
 */
export interface HomePage {
  id: number;
  motionPreset?: ('off' | 'stretch') | null;
  hero: {
    eyebrow?: string | null;
    headline: string;
    copy: string;
    slides?:
      | {
          image: number | ImageAsset;
          caption?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  calculator: {
    headline: string;
    copy: string;
  };
  contact: {
    headline: string;
    copy: string;
  };
  seo?: {
    title?: string | null;
    description?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery-page".
 */
export interface GalleryPage {
  id: number;
  headline: string;
  copy: string;
  seo?: {
    title?: string | null;
    description?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page".
 */
export interface AboutPage {
  id: number;
  headline: string;
  intro: string;
  values?:
    | {
        title: string;
        copy: string;
        id?: string | null;
      }[]
    | null;
  image?: (number | null) | ImageAsset;
  seo?: {
    title?: string | null;
    description?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Editable calculator rules. The public result is an approximate range, not a final offer.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pricing-settings".
 */
export interface PricingSetting {
  id: number;
  /**
   * Enable only after reviewing all prices, translations and VAT wording. Otherwise visitors can contact you without a numeric quote.
   */
  approved?: boolean | null;
  basePriceRonPerSqm: number;
  minimumProjectRon: number;
  eurRate: number;
  rangePercent: number;
  vatMode: 'not-specified' | 'included' | 'excluded';
  ceilingTypes?:
    | {
        label: string;
        value: string;
        multiplier: number;
        id?: string | null;
      }[]
    | null;
  lightingOptions?:
    | {
        label: string;
        value: string;
        fixedRon: number;
        perSqmRon: number;
        id?: string | null;
      }[]
    | null;
  complexityOptions?:
    | {
        label: string;
        value: string;
        multiplier: number;
        id?: string | null;
      }[]
    | null;
  cityFees?:
    | {
        city: string;
        fixedRon: number;
        id?: string | null;
      }[]
    | null;
  fallbackTravelFeeRon: number;
  disclaimer?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Only enabled, translated items appear publicly. Keep unconfirmed services unpublished.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  items?:
    | {
        enabled?: boolean | null;
        title: string;
        description: string;
        customQuote?: boolean | null;
        id?: string | null;
      }[]
    | null;
  architects?: {
    enabled?: boolean | null;
    title?: string | null;
    description?: string | null;
  };
  process?:
    | {
        title: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  faq?:
    | {
        enabled?: boolean | null;
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  brandName?: T;
  domain?: T;
  logoImage?: T;
  phone?: T;
  email?: T;
  whatsappNumber?: T;
  facebookUrl?: T;
  instagramUrl?: T;
  legalName?: T;
  registrationNumber?: T;
  mainCity?: T;
  serviceArea?: T;
  serviceCities?:
    | T
    | {
        city?: T;
        id?: T;
      };
  palette?:
    | T
    | {
        warmNeutral?: T;
        orange?: T;
        blue?: T;
        black?: T;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        defaultOgImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation-footer_select".
 */
export interface NavigationFooterSelect<T extends boolean = true> {
  headerLinks?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  footerLinks?:
    | T
    | {
        label?: T;
        href?: T;
        newTab?: T;
        id?: T;
      };
  footerText?: T;
  creditLabel?: T;
  creditHref?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page_select".
 */
export interface HomePageSelect<T extends boolean = true> {
  motionPreset?: T;
  hero?:
    | T
    | {
        eyebrow?: T;
        headline?: T;
        copy?: T;
        slides?:
          | T
          | {
              image?: T;
              caption?: T;
              id?: T;
            };
      };
  calculator?:
    | T
    | {
        headline?: T;
        copy?: T;
      };
  contact?:
    | T
    | {
        headline?: T;
        copy?: T;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery-page_select".
 */
export interface GalleryPageSelect<T extends boolean = true> {
  headline?: T;
  copy?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page_select".
 */
export interface AboutPageSelect<T extends boolean = true> {
  headline?: T;
  intro?: T;
  values?:
    | T
    | {
        title?: T;
        copy?: T;
        id?: T;
      };
  image?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pricing-settings_select".
 */
export interface PricingSettingsSelect<T extends boolean = true> {
  approved?: T;
  basePriceRonPerSqm?: T;
  minimumProjectRon?: T;
  eurRate?: T;
  rangePercent?: T;
  vatMode?: T;
  ceilingTypes?:
    | T
    | {
        label?: T;
        value?: T;
        multiplier?: T;
        id?: T;
      };
  lightingOptions?:
    | T
    | {
        label?: T;
        value?: T;
        fixedRon?: T;
        perSqmRon?: T;
        id?: T;
      };
  complexityOptions?:
    | T
    | {
        label?: T;
        value?: T;
        multiplier?: T;
        id?: T;
      };
  cityFees?:
    | T
    | {
        city?: T;
        fixedRon?: T;
        id?: T;
      };
  fallbackTravelFeeRon?: T;
  disclaimer?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  items?:
    | T
    | {
        enabled?: T;
        title?: T;
        description?: T;
        customQuote?: T;
        id?: T;
      };
  architects?:
    | T
    | {
        enabled?: T;
        title?: T;
        description?: T;
      };
  process?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  faq?:
    | T
    | {
        enabled?: T;
        question?: T;
        answer?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}